language: python

python:
        - 3.6

sudo: required
dist: trusty
addons: 
        postgresql: "9.6"

services:
        - postgresql

env:
        - DJANGO_SETTINGS_MODULE="grooving-server.server.Grooving"

install:
        - pip install -r grooving-server/Server/requirements.txt

before_script:
        - psql -c "psql -c create user root with password 'root'" -U postgres
        - psql -c "create database grooving owner root"

script:
	- python grooving-server/Server/manage.py makemigrations
        - python grooving-server/Server/manage.py migrate
        # python ./manage.py test ./manage.py
